---
server:
  port: 8020

---

spring:
  application:
    name: "gasprice-service"


  boot:
    admin:
      client:
        instance:
          prefer-ip: true
        url: http://161.97.103.17:8100
  datasource:
    url: jdbc:postgresql://161.97.103.17:5432/gasprice
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1808grshsrg
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true




logging:
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: INFO
  file:
    name: "/var/log/gasprice/chat-service.log"

management:
  endpoints:
    web:
      exposure:
        include: "*"




